import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/lesson_plan_provider.dart';
import '../theme/app_theme.dart';
import '../widgets/app_background.dart';
import 'sound_lesson_page.dart';

/// Roadmap progress page — shows topic-by-topic progress and the next
/// personalized lesson generated by the LLM.
class ProgressRoadmapPage extends ConsumerStatefulWidget {
  final bool isActive;
  const ProgressRoadmapPage({super.key, this.isActive = true});

  @override
  ConsumerState<ProgressRoadmapPage> createState() =>
      _ProgressRoadmapPageState();
}

class _ProgressRoadmapPageState extends ConsumerState<ProgressRoadmapPage> {
  bool _hasLoaded = false;

  @override
  void initState() {
    super.initState();
    if (widget.isActive) {
      _loadData();
    }
  }

  @override
  void didUpdateWidget(ProgressRoadmapPage oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.isActive && !oldWidget.isActive && !_hasLoaded) {
      _loadData();
    }
  }

  void _loadData() {
    _hasLoaded = true;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(lessonPlanProvider.notifier).loadAll();
    });
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(lessonPlanProvider);
    final theme = Theme.of(context);

    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        title: const Text('Mi Progreso'),
        actions: [
          if (!state.isLoading)
            IconButton(
              icon: const Icon(Icons.refresh),
              tooltip: 'Actualizar',
              onPressed: () =>
                  ref.read(lessonPlanProvider.notifier).loadAll(),
            ),
        ],
      ),
      body: AppBackground(
        child: SafeArea(
          child: _buildBody(context, state, theme),
        ),
      ),
    );
  }

  Widget _buildBody(
      BuildContext context, LessonPlanState state, ThemeData theme) {
    if (state.isLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    if (state.error != null) {
      return _ErrorView(
        error: state.error!,
        onRetry: () => ref.read(lessonPlanProvider.notifier).loadAll(),
      );
    }

    if (state.roadmap == null && state.plan == null) {
      return const Center(
        child: Text('No hay datos de progreso disponibles.'),
      );
    }

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // ── Next lesson card ─────────────────────────────────────────────
        if (state.plan != null) ...[
          _SectionHeader(title: 'Próxima lección', icon: Icons.auto_awesome),
          const SizedBox(height: 8),
          _LessonCard(plan: state.plan!, theme: theme),
          const SizedBox(height: 24),
        ],

        // ── Roadmap topics ───────────────────────────────────────────────
        if (state.roadmap != null &&
            state.roadmap!.topics.isNotEmpty) ...[
          _SectionHeader(
            title: 'Hoja de ruta — ${state.roadmap!.lang.toUpperCase()}',
            icon: Icons.map_outlined,
          ),
          const SizedBox(height: 8),
          ...state.roadmap!.topics
              .map((t) => _TopicCard(topic: t, theme: theme)),
        ],
      ],
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Sub-widgets
// ─────────────────────────────────────────────────────────────────────────────

class _SectionHeader extends StatelessWidget {
  final String title;
  final IconData icon;
  const _SectionHeader({required this.title, required this.icon});

  @override
  Widget build(BuildContext context) {
    final style = Theme.of(context).textTheme.titleMedium;
    return Row(
      children: [
        Icon(icon, size: 20),
        const SizedBox(width: 8),
        Text(title, style: style?.copyWith(fontWeight: FontWeight.bold)),
      ],
    );
  }
}

class _LessonCard extends StatelessWidget {
  final LessonPlan plan;
  final ThemeData theme;
  const _LessonCard({required this.plan, required this.theme});

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Intro
            if (plan.intro.isNotEmpty) ...[
              Text(plan.intro, style: theme.textTheme.bodyMedium),
              const SizedBox(height: 12),
            ],

            // LLM metadata
            if (plan.meta.containsKey('llm_model')) ...[
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: theme.colorScheme.primaryContainer,
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.psychology, size: 14, color: theme.colorScheme.onPrimaryContainer),
                    const SizedBox(width: 4),
                    Text(
                      'Generado por: ${plan.meta['llm_model']}',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: theme.colorScheme.onPrimaryContainer,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 12),
            ],

            // Tips
            if (plan.tips.isNotEmpty) ...[
              Text('Consejos',
                  style: theme.textTheme.labelLarge
                      ?.copyWith(fontWeight: FontWeight.bold)),
              const SizedBox(height: 6),
              ...plan.tips.map(
                (tip) => Padding(
                  padding: const EdgeInsets.only(bottom: 4),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('• ', style: TextStyle(fontSize: 16)),
                      Expanded(child: Text(tip)),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 12),
            ],

            // Drills
            if (plan.drills.isNotEmpty) ...[
              Text('Ejercicios',
                  style: theme.textTheme.labelLarge
                      ?.copyWith(fontWeight: FontWeight.bold)),
              const SizedBox(height: 6),
              ...plan.drills.map(
                (d) => Padding(
                  padding: const EdgeInsets.only(bottom: 6),
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 12, vertical: 8),
                    decoration: BoxDecoration(
                      color: theme.colorScheme.surfaceContainerHighest
                          .withAlpha(120),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          d.type == 'listen'
                              ? Icons.headphones
                              : d.type == 'repeat'
                                  ? Icons.mic
                                  : Icons.edit_outlined,
                          size: 16,
                          color: theme.colorScheme.secondary,
                        ),
                        const SizedBox(width: 8),
                        Expanded(child: Text(d.text)),
                      ],
                    ),
                  ),
                ),
              ),
            ],

            // CTA
            if (plan.recommendedSoundId.isNotEmpty) ...[
              const SizedBox(height: 12),
              Align(
                alignment: Alignment.centerRight,
                child: FilledButton.icon(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => SoundLessonPage(
                          soundId: plan.recommendedSoundId,
                          ipa: plan.recommendedSoundId,
                          name: 'Práctica: ${plan.recommendedSoundId}',
                        ),
                      ),
                    );
                  },
                  icon: const Icon(Icons.play_arrow),
                  label: Text('Practicar ${plan.recommendedSoundId}'),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

class _TopicCard extends StatelessWidget {
  final RoadmapTopic topic;
  final ThemeData theme;
  const _TopicCard({required this.topic, required this.theme});

  Color _levelColor(String level) {
    switch (level) {
      case 'completed':
        return Colors.green;
      case 'proficient':
        return Colors.teal;
      case 'in_progress':
        return Colors.orange;
      default:
        return Colors.grey;
    }
  }

  @override
  Widget build(BuildContext context) {
    final color = _levelColor(topic.level);
    return Card(
      margin: const EdgeInsets.only(bottom: 10),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                  child: Text(
                    topic.name,
                    style: theme.textTheme.titleSmall
                        ?.copyWith(fontWeight: FontWeight.w600),
                  ),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 10, vertical: 3),
                  decoration: BoxDecoration(
                    color: color.withAlpha(40),
                    border: Border.all(color: color),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(
                    topic.levelLabel,
                    style:
                        TextStyle(color: color, fontSize: 12),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            ClipRRect(
              borderRadius: BorderRadius.circular(4),
              child: LinearProgressIndicator(
                value: topic.progress,
                minHeight: 6,
                backgroundColor:
                    theme.colorScheme.surfaceContainerHighest,
                valueColor: AlwaysStoppedAnimation<Color>(color),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ErrorView extends StatelessWidget {
  final String error;
  final VoidCallback onRetry;
  const _ErrorView({required this.error, required this.onRetry});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.wifi_off, size: 48, color: Colors.grey),
            const SizedBox(height: 12),
            Text(
              'No se pudo cargar el progreso',
              style: Theme.of(context).textTheme.titleMedium,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 6),
            Text(
              error,
              style: Theme.of(context)
                  .textTheme
                  .bodySmall
                  ?.copyWith(color: Colors.grey),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 16),
            OutlinedButton.icon(
              onPressed: onRetry,
              icon: const Icon(Icons.refresh),
              label: const Text('Reintentar'),
            ),
          ],
        ),
      ),
    );
  }
}
